#include "register/tilingdata_base.h"

constexpr uint8_t   MAX_SHAPE_SIZE  = 4;

namespace optiling {
  BEGIN_TILING_DATA_DEF(SelectV2TilingData)
  TILING_DATA_FIELD_DEF(uint32_t, placeHolder)
  END_TILING_DATA_DEF
  
  BEGIN_TILING_DATA_DEF(SelectV2TilingDataNoBC)
  TILING_DATA_FIELD_DEF(uint32_t, tileLength)
  TILING_DATA_FIELD_DEF(uint32_t, tileNumber)
  TILING_DATA_FIELD_DEF(uint32_t, reminder)
  END_TILING_DATA_DEF

  BEGIN_TILING_DATA_DEF(SelectV2TilingDataBC)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, condShape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, condShapeRSum)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, x1Shape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, x1ShapeRSum)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, x2Shape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, x2ShapeRSum)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, yShape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, yShapeRSum)
  TILING_DATA_FIELD_DEF(uint32_t, shapeSize)
  TILING_DATA_FIELD_DEF(uint32_t, dataLength)
  END_TILING_DATA_DEF

  BEGIN_TILING_DATA_DEF(SelectV2TilingDataBCWithMiniBatch)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, condShape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, condShapeRSum)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, x1Shape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, x1ShapeRSum)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, x2Shape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, x2ShapeRSum)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, yShape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, yShapeRSum)
  TILING_DATA_FIELD_DEF(uint32_t, shapeSize)
  TILING_DATA_FIELD_DEF(uint32_t, tileLength)
  TILING_DATA_FIELD_DEF(uint32_t, tileNumber)
  TILING_DATA_FIELD_DEF(uint32_t, reminder)
  TILING_DATA_FIELD_DEF(uint32_t, bigBatch)
  END_TILING_DATA_DEF

  REGISTER_TILING_DATA_CLASS(SelectV2, SelectV2TilingData)
  REGISTER_TILING_DATA_CLASS(SelectV2_1, SelectV2TilingDataNoBC)
  REGISTER_TILING_DATA_CLASS(SelectV2_2, SelectV2TilingDataBC)
  REGISTER_TILING_DATA_CLASS(SelectV2_3, SelectV2TilingDataBCWithMiniBatch)
}
