
#include "register/tilingdata_base.h"
constexpr uint8_t   MAX_SHAPE_SIZE  = 4;
namespace optiling {
BEGIN_TILING_DATA_DEF(PowsTilingData)
  TILING_DATA_FIELD_DEF(uint8_t, placeholder)
END_TILING_DATA_DEF

BEGIN_TILING_DATA_DEF(PowsTilingDataNoBC)
TILING_DATA_FIELD_DEF(uint32_t, tileLength)
TILING_DATA_FIELD_DEF(uint32_t, maxLength)
TILING_DATA_FIELD_DEF(uint32_t, reminder)
END_TILING_DATA_DEF

BEGIN_TILING_DATA_DEF(PowsTilingDataBC)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, x1Shape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, x1ShapeRSum)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, x2Shape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, x2ShapeRSum)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, yShape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, yShapeRSum)
  TILING_DATA_FIELD_DEF(uint32_t, shapeSize)
  TILING_DATA_FIELD_DEF(uint32_t, dataLength)
END_TILING_DATA_DEF

BEGIN_TILING_DATA_DEF(PowsTilingDataBCWithMiniBatch)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, x1Shape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, x1ShapeRSum)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, x2Shape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, x2ShapeRSum)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE, yShape)
  TILING_DATA_FIELD_DEF_ARR(uint32_t, MAX_SHAPE_SIZE + 1, yShapeRSum)
  TILING_DATA_FIELD_DEF(uint32_t, shapeSize)
  TILING_DATA_FIELD_DEF(uint32_t, tileLength)
  TILING_DATA_FIELD_DEF(uint32_t, maxLength)
  TILING_DATA_FIELD_DEF(uint32_t, reminder)
  TILING_DATA_FIELD_DEF(uint32_t, bigBatch)
END_TILING_DATA_DEF

REGISTER_TILING_DATA_CLASS(Pows, PowsTilingData)
REGISTER_TILING_DATA_CLASS(Pows_1, PowsTilingDataNoBC)
REGISTER_TILING_DATA_CLASS(Pows_2, PowsTilingDataBC)
REGISTER_TILING_DATA_CLASS(Pows_3, PowsTilingDataBC)
REGISTER_TILING_DATA_CLASS(Pows_4, PowsTilingDataBCWithMiniBatch)
}
